export const DEFAULT_WIDTH_MULTIPLICATION = 14
export const DEFAULT_PAGESIZES = [5, 10, 20, 50, 100]
export const DEFAULT_VIEW_MODE_PAGING = 'PAGING'
export const DEFAULT_VIEW_MODE_ALL_DATA = 'ALL_DATA'
export const DEFAULT_VIEW_MODE_GROUPING = 'GROUPING'

export const DEFAULT_VIEW_MODE_OPTIONS = [
  {
    value: DEFAULT_VIEW_MODE_PAGING,
    label: 'Paging',
  },
]

export const LOCAL_VIEW_MODE = 'LOCAL_VIEW_MODE'
export const LOCAL_HIDDEN_COLUMNS = 'LOCAL_HIDDEN_COLUMNS'
export const LOCAL_REORDER_COLUMNS = 'LOCAL_REORDER_COLUMNS'
export const LOCAL_RESIZE_COLUMNS = 'LOCAL_RESIZE_COLUMNS'
export const LOCAL_GROUPING_ROWS = 'LOCAL_GROUPING_ROWS'
export const LOCAL_PARAM_PER_PAGE = 'LOCAL_PARAM_PER_PAGE'
export const LOCAL_PARAM_PAGE_SIZES = 'LOCAL_PARAM_PAGE_SIZES'
export const LOCAL_COLUMN_TABLES = 'LOCAL_COLUMN_TABLES'
export const LOCAL_FIXED_COLUMNS = 'LOCAL_FIXED_COLUMNS'
export const LOCAL_FILTERS = 'LOCAL_FILTERS'
export const LOCAL_FILTER_SETTINGS = 'LOCAL_FILTER_SETTINGS'
export const LOCAL_PERMISSIONS = 'LOCAL_PERMISSIONS'
