name: Core UI CI

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Deploy
              env:
                  PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY_DEV }}
                  USER_NAME: ubuntu
                  HOST_NAME: 65.2.3.165
              run: |
                  mkdir -p ~/.ssh
                  echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
                  chmod 700 ~/.ssh/id_rsa
                  eval $(ssh-agent -s)
                  rsync -avzr -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' ./ $USER_NAME@$HOST_NAME:/home/ubuntu/gmb-reactjs-2/
                  ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USER_NAME@$HOST_NAME "cd gmb-reactjs-2 && yarn && yarn build"
